### ISSUE TITLE
Feature Request: System Settings Theme (Light/Dark)

### ISSUE THREAD

**Issue by parkuman** [mattermost/focalboard#116]
**Summary:**
Allow the user to select `System` as an option for their theme. It will use their OS preferred color scheme of light/dark.

**How important this is to me and why:**

Importance: Low, but it isn't a feature in Notion!

Use cases:
People like their apps to appear seamless with their OS. In MacOS and Windows switching between light/dark mode and seeing all your supported apps switch feels great. This is perfect for setups that automatically switch the OS theme depending on the time of day - in MacOS this is a setting provided by Apple, in windows, there's this great program: https://github.com/Armin2208/Windows-Auto-Night-Mode I've been using. 

**Implementation:**
The CSS media selector `@media (prefers-color-scheme: dark) {` is a super easy way to implement this feature. Looking at the way themes are handled in theme.tsx using json and assigning values to CSS variables, what's the best way we could implement this?

**Comment by jespino** [comment]
Thanks for the suggestion, I think this can be a good first issue for somebody.

**Comment by jespino** [comment]
Done on #145 (but still needs some testing)

**Comment by chenilim** [comment]
This was done in v0.6.5. There's a new "System theme" setting in themes. Closing.

**Comment by perlator** [comment]
Hi there! 👋

Thanks for implementing the automatic dark/light theme switching feature - it's really appreciated! 

I noticed that the current implementation works great on Windows and macOS, but it looks like Linux support might have been overlooked. Would it be possible to add Linux compatibility in a future update? 

Many Linux desktop environments (GNOME, KDE, XFCE, etc.) now support the `prefers-color-scheme` media query or have their own theme detection mechanisms that could be leveraged.

No rush on this - just wanted to bring it to your attention since us penguin users would love to enjoy this feature too! 🐧

Thanks again for all the great work on this project!

**Comment by zyga** [comment]
I'm using mattermost desktop 5.13.1 and I don't have any such option. I used the official windows client.
