### ISSUE TITLE
Request to update windows store focalbord to a later version more frequently.

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#1181]
**Summary:**
Right now the windows store version is on v0.8.0.  

- Items fail to drag properly at times, or do not update to their correct position, requiring a closing and re-opening of the screen..
- The top headers do not scroll with the rest of the items.
- The page randomly resets and items become hidden or unhidden.
- The width of the screen doesn't properly scale to items so there are buttons you cannot click due to being off screen with no scrollbar to access them.

**How important this is to me and why:**
The state of the program is near unusable - Normally being on the latest update isn't that big of a deal, but I believe a frequent release should be prioritized when they're so crippling for the UX.

Importance: High

**Comment by chenilim** [comment]
Thanks for reporting these issues @tjbortz1s! Definitely noted. Long story short, the issues above should be fixed in v0.9, but our schedule was impacted, and it should be released in 1-2 weeks time. Normally, the App Stores should be updated once a month.

In the meantime, if you would like, please check out the [v0.9.0 RC9 release](https://github.com/mattermost/focalboard/releases/tag/v0.9.0-rc9) - you can install the unsigned windows .zip file directly. Thanks!

**Comment by tjbortz1s** [comment]
Managed to flip over to the windows zip build and that's working a ton better.  
I'll use that instead of the windows store going forward, thank you.
