### ISSUE TITLE
Bug: uncaught TypeError for person property type in single user mode

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1192]
**Steps to reproduce the behavior:**
1. Start server in a single user mode (or use any desktop app)
2. Create new board
3. Create new card
4. Add new property and change its type to `person`
5. Uncaught TypeError: Cannot read properties of undefined (reading 'toString')

**Expected behavior:**
There should be no exception. Before it just showed "No option" in the select menu.

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
Regression was introduced in #1174
@sbishel FYI

**Comment by sbishel** [comment]
This issue has already been fixed in this PR. (Merged after this was written.)
https://github.com/mattermost/focalboard/pull/1178

The offending PR had not been cherry picked to release-0.9.0.
So the CP was updated to contain this fix as well. 
https://github.com/mattermost/focalboard/commit/26dba73f007296d9fba68fbda5d85886db8d3609
