### ISSUE TITLE
Bug: Predefined templates are missing

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1237]
**Steps to reproduce the behavior:**
1. Go to Boards
2. Click on _Add board_
3. Observe the empty templates list

**Expected behavior:**
All the predefined templates should be listed

**Screenshots:**
![templates](https://user-images.githubusercontent.com/15314183/133692140-10c3abb8-16b9-4f59-988b-18a3557162b3.jpg)

**Edition and Platform:**
Plugin v0.9.0 RC12 on community

 - Edition: Mattermost plugin
 - Version: v0.9.0 RC12
 - Browser and OS: Chrome 93 on Windows

**Comment by chenilim** [comment]
@harshilsharma63, I took a quick look at this. The root cause is this [new logic in octoClient](https://github.com/mattermost/focalboard/blob/main/webapp/src/octoClient.ts#L136) to default to the last workspace if `workspaceId === 0`.

The problem is [globalTemplates.ts](https://github.com/mattermost/focalboard/blob/main/webapp/src/store/globalTemplates.ts#L14) creates a new OctoClient with `workspaceId === 0` specifically to load the global templates (which are on workspaceId 0).

Not sure what the best fix is, but some ideas:
* Revert this line of logic (not sure of the impact)
* Change the default workspaceId of octoClient to undefined (so 0 is a valid workspaceId to use for global templates)
* Some other way to force loading the blocks from workspaceId 0 for global templates.
