### ISSUE TITLE
Bug: Issue with WebSocket, not getting events after changing.

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#1270]
**Steps to reproduce the behavior:**
Seems if you get into the state, it reproduced everytime, but not sure how to get into that status.

1. Go to "New Card"
2. Click on Title
3. Change Title.
4. Close Card
5. Card does not show title changes.
6. Refresh, title changes now there.

Also, properties or any changes exhibit the same behavior

**Expected behavior:**
Changes should be saved and updated in the UI

**Screenshots:**

**Edition and Platform:**
 - Edition: Mattermost plugin
 - Version: v0.9.0 RC12
 - Browser and OS: [ 93.0.4577.82 (Official Build) (x86_64) on macO]

**Additional context:**
Hard to repo on demand. 

https://user-images.githubusercontent.com/12704875/134034209-d067d7b0-6592-430e-a987-edb15c9153df.mp4

**Comment by chenilim** [comment]
@mgdelacroix, I ran a [dev build](https://github.com/mattermost/focalboard/actions/runs/1270631272) on the `release-0.9.0` branch, and observed the following issue:
1. Install and enable plugin on test server (`/cloud create SERVERNAME --version master`)
2. Switch to Boards via the App Switcher
3. Try to drag a card to another column
4. The card doesn't move (but does move after Cmd+R refresh)

However, this works if Boards is opened via the channel header button. In that case, both Boards tabs work.
1. Click on Boards button in channel header
2. Drag and drop cards - this works
3. In separate tab, open Boards again from the App Switcher
4. Drag and drop cards - this works now
5. Close the tab opened from the channel header
6. Drag and drop cards (in the tab opened from the App Switcher - this stops working

Video:
https://user-images.githubusercontent.com/46905241/134717143-15e39bf6-63d8-44ea-b876-72141f92f961.mov

Not sure if this will be fixed by the attached PR, but I believe this is the same issue. LMK if not, and we can create a separate issue, but this should be fixed before the next RC too.
cc @ogi-m, please also test these steps when verifying the fix. Thanks.

**Comment by mgdelacroix** [comment]
@chenilim I've been investigating this a bit and it seems that is related to the URL schema and the subscription message. When navigating to a URL with the schema `/boards/{{boardId}}/{{viewId}}` the frontend sends a subscription message for the workspace id `0`. The updates are not received because the client never gets to subscribe properly.

If the URL has the `boards/workspace/{{workspaceId}}/{{boardId}}/{{viewId}}`, the subscription message correctly sends the workspace ID and everything works fine.

@jespino @harshilsharma63 could you please take a stab at solving this?

**Comment by mgdelacroix** [comment]
Agree with your analysis @chenilim, but looking into this further, I think the bug is a level above what we're experiencing. When clicking into the app switcher, the resulting URL is `/boards/dashboard`, but the dashboard component is not being rendered, we see a workspace instead with a URL that doesn't provide with its ID, hence the subscription issue. Going to the dashboard and then to a workspace works as expected and subscribes correctly.

When navigating to Boards from the app switcher button, do we want to see the dashboard or the last visited workspace? If it's the former, we're showing the wrong component, and if it's the latter, we're redirecting the tab to the wrong URL.

**Comment by mgdelacroix** [comment]
Actually, this has been already taken care of here https://github.com/mattermost/focalboard/issues/1337
