### ISSUE TITLE
Don't show an error when the Boards plugin is updated, or server connection interrupted

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1316]
**Summary:**
Currently, users with a Boards tab open see an error when the plugin is updated:
1. Go to system console
2. Update the Boards plugin
3. All clients see an error (can press the back button to return to the board)

***Expected:***
Users see the board they were on after the update is completed.

**Additional context:**
This likely requires the websocket error handling code to be tweaked. Currently, it switches to polling after a period (5 seconds). However, if the plugin is disabled (or connection interrupted) during the poll, this results in a general error, because the route is not found.

In general, Boards should have a similar error-handling experience to Channels, i.e. to show an intermittent error banner when the connection is interrupted, but seamlessly recovering after the connection is restored.

**Comment by chenilim** [comment]
@sbishel, there will be fit and finish bugs / features like this as we converge on v1. Not sure what the best way to collect them is, but I think we can file issues here, then collect the high-pri ones in a card for specific releases? We can chat more.

**Comment by mgdelacroix** [comment]
@chenilim Could not reproduce this exact behaviour. With the current server `master`, what's happening is that the plugin gets restarted server side and reloaded client side. The consequence of this is that the server loses the websockets connections data, so the client needs to reconnect.

A quick way of solving this is to refresh the page on plugin update, as the websocket connection is getting a notification when the plugin changes its status. This solution has been drafted at https://github.com/mattermost/focalboard/pull/1720

A more precise solution in which we reconnect instead of reload from the client could be possible, but will require further investigation as it doesn't seem as simple as reconnecting when the plugin update message is received.

**Comment by ogi-m** [comment]
Verified the banner is appearing as expected on latest v0.10 branch
