### ISSUE TITLE
Bug: Dashboard shows double username for private channel

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#1484]
## Steps to reproduce the behavior

1. Go to private single user channel in Channels
2. Select  Boards from app switcher
3. See strange double username displayed for that board

## Expected behavior
Single username (or similar)

## Screenshots
![dashboard](https://user-images.githubusercontent.com/5024605/136411802-e7f3ab93-220f-4fb8-b5ef-8473feaf14e1.png)
## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.x
 - Browser and OS: Linux, Firefox 93

**Comment by harshilsharma63** [comment]
[Over here](https://github.com/mattermost/focalboard/blob/f6c867b4afe8ee6e0e0abef536192d4a8c61d2c1/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L435) in the API we split the channel name to get the two user's ID between whom the DM channel is. We can add a check if both user IDs are the same, then return the display name as just the first user's name.

**Comment by ssensalo** [comment]
I adjusted [Here](https://github.com/mattermost/focalboard/blob/f6c867b4afe8ee6e0e0abef536192d4a8c61d2c1/webapp/src/pages/dashboard/centerContent.tsx#L96) to achieve exactly what @wiggin77 & @chenilim suggested since they intend to replace channel based permissions with board based permissions.
Only that I am current having env setup issues, I hope to fix those soon and make a PR

**Comment by sbishel** [comment]
Closing as no longer necessary.
