### ISSUE TITLE
Feature Request: Columns should have a min-width to fit content including category labels

### ISSUE THREAD

**Issue by daftaupe** [mattermost/focalboard#153]
**Summary:**
I added some custom category label and it seems that the columns in table view doesn't adapt as one of my label is being written on top of the column delimiter.

**Steps to reproduce the behavior:**
1. Create a label with more than 9 or 10 letters depending on the letters used
2. Click on table view
3. The category name is displayed on the next column

**Expected behavior:**
The column width should adapt to the longest label, or longer labels than the column width should be truncated.

**Screenshots:**
![Screenshot_2021-03-20 Perso Tâches](https://user-images.githubusercontent.com/22810624/111882838-05d89580-89b8-11eb-9c94-a9cbf21b6685.png)

**Platform:**
 - Firefox 86.0.1
 - FreeBSD 13-RC2

**Additional context:**
Focalboard 0.6.1

**Comment by chenilim** [comment]
Thanks for submitting this issue @daftaupe! The root problem is the table columns don't (yet) support auto-fit, or minimum-width. I'm changing this to a feature request to track that.

The **workaround** is to manually resize the column by dragging the border between columns in the header.

Open to community contributions. It's tricky because the width would need to be calculated after rendering (or use some kind of estimated width based on the contents). Ideally, the user can still manually set the column width, but it will at a minimum be the width of the longest item.

Bonus points: Double-clicking on the column border should auto-size to fit the longest item.

There's a related issue where the contents of the cells don't clip (I opened #154 to track that).

**Comment by daftaupe** [comment]
Thanks for workaround @chenilim 
For the rest I really can't help, sorry, but I like the bonus point :)

**Comment by jespino** [comment]
This should be fixed in the main branch.
