### ISSUE TITLE
Bug: Emoji icons show grey on main board but not when adding new card.

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#1697]
## Steps to reproduce the behavior

I honestly have no idea.  I think I accidentally opened the F12 menu at some point and this seemed to happen at around this time.  I looked in the CSS and couldn't find a trace of why the icons are looking this way.

Main board
![image](https://user-images.githubusercontent.com/6193065/139340007-b24687b7-00d4-4a9b-8a41-888d8df47091.png)
Editing
![image](https://user-images.githubusercontent.com/6193065/139340017-a7a09fbb-cf52-4d90-8ac2-87425fee226a.png)

## Expected behavior

Image on main board appears the same as on the editing area.

## Edition and Platform

 - Windows app
 - Version: 0.9.1 and 0.10.0
 - Windows 10

**Comment by chenilim** [comment]
No idea why the outline is thicker on zoomed out emojis on Windows. Anyone know? Putting it up for grabs.

**Comment by starlocke** [comment]
I had installed Focalboard on Windows 10 sometime in 2021 (Spring? Summer?) and the emoji were working fine in full-colour. Suddenly, something changed and they were no longer in full-colour. Huge disappointment.

I played with the web-inspector today... it turns out that the culprit here is "font-weight: 600" overriding "font-weight: 500" in the stylesheets.

I suppose that "Segoe UI Emoji" in the "bold" (font-weight: 600) style does not have colour versions and turns itself into "bolded outline" versions of itself.

**Comment by starlocke** [comment]
Here's the evidence about font-weight:

![image](https://user-images.githubusercontent.com/1019999/143461926-8dda08fb-eb34-4e2a-9aa6-11ddbaef336d.png)

Another interesting observation is this, below -- in the "main body" of the view, the emoji lives in its own `<span>` , for some reason. This "separation of concerns" might be a hint towards an easy solution like "wrap all the emoji in <span class='emoji'> and setting the font-weight back down to 500 using that CSS class".

![image](https://user-images.githubusercontent.com/1019999/143462319-e2153202-0bb0-44a8-af9f-6047c91b0555.png)

**Comment by tjbortz1s** [comment]
I noticed this same effect just this morning and came here to say the same - I can confirm that the font weight is what was breaking the app for me as well, and if I turn off font weight the emotes go back to normal.

This has fallen way down in the issue list though, I hope that maybe a ping to @chenilim   might get some attention on this - because it may be an easy fix and while I'd love to do it here I am not set up to try to do this.

**Comment by tjbortz1s** [comment]
@starlocke in the meantime you can actually go into "main.js" inside of your focalboard install (assuming you're not using the windows store version) and change "font-weight: 600" to 500 after "octo-icontitle" and that makes a semi-permanent fix to the CSS without needing the project to implement any fixes.

![image](https://user-images.githubusercontent.com/6193065/143935800-fbb633e8-a6de-41c3-ae96-a00f12be1727.png)

main.js contained here.
![image](https://user-images.githubusercontent.com/6193065/143935850-42610dd6-5566-4197-aa6c-c42008c25640.png)

**Comment by starlocke** [comment]
@tjbortz1s I am actually a user of the Windows Store edition of Focalboard, so, for me, it's a terrible to go mucking around inside of `C:\Program Files\WindowsApps\`.

**Comment by starlocke** [comment]
Okay. So... I ended up scrambling to find a Windows edition of Focalboard that isn't from the Windows Store (ex: [v0.10.0](https://github.com/mattermost/focalboard/releases/tag/v0.10.0)) and the suggested workaround was helpful. I ended up just changing all `font-weight:600` to `font-weight:500` and the glorious, technicolor goodness of _Segoe UI Emoji_  was restored.

It was a simple matter to export the data from the Windows Store edition and then import it into the ".zip" distribution.

**Comment by starlocke** [comment]
Curiously enough... The "Roadmap" board's "Epic" view seems to employ a funny-looking "mountain" emoji.

At first, I thought it was another `font-weight` issue (it's not).

![image](https://user-images.githubusercontent.com/1019999/143947550-f5f792e6-b863-4cd7-80e2-c91ee257023f.png)

Then I noted that it was really just a different emoji symbol that happens to not render properly for whatever reason. Maybe my system doesn't have this emoji colorized in its font bank. The evidence? The "personal goals" emoji could be copy-pasted next to the "epics" one and it would render just fine.

![image](https://user-images.githubusercontent.com/1019999/143948741-2dda2ed1-d903-4464-b5ae-ddd6b673fb0d.png)

Note that I personally don't care enough to commit a whole, heavy-weight "issue report" for this little emoji quirk (ie: the template probably needs to be tweaked). I'm just leaving it here because it's relevant as a "why did that one icon not get colourized?" observation.

**Comment by tjbortz1s** [comment]
Closing this as the icon issue was closed in the duplicate issue as well.
