### ISSUE TITLE
Write Focalboard E2E with Cypress: "MM-T4291 Group by different property"

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/focalboard#1826]
<article>
<h1>MM-T4291 Group by different property</h1>
<div>
<div>
<hr><h3>Steps  #1</h3>Create an empty board and <a href="https://automation-test-cases.vercel.app/test/MM-T4284">add a group</a><h3><h3>Steps  #2</h3>Click "+New" in "Group 1" to add a card<h3>Expected</h3>A new card is added to the group and the card dialog opens<hr><h3>Steps  #3</h3>Click on "Add a property"<h3>Expected</h3>Property titled "New Property" is created<hr><h3>Steps  #4</h3>Click on "New Property", hover on "Type:Text" and change the property type to "Select"<h3>Expected</h3>Property type changed from "Text" to "Select"<hr><h3>Steps  #5</h3>Close the card dialog and click on "Group by"<h3>Expected</h3>Dropdown opens showing "Status" and "New Property", with a checkmark next to "Status"<hr><h3>Steps  #6</h3>Change the selection to "New Property"<h3>Expected</h3>Card is moved to "No New Property" Group<hr><h3>Steps  #7</h3>Click on "+Add a group"<h3>Expected</h3>"New Group" is created<hr><h3>Steps  #8</h3>Click "+New" in the "New Group" column to create a new card<h3>Expected</h3>Card dialog opens and "New Group" is set as the "New Property" value<hr>
</div>
</div>
</article>

**Test code arrangement:**
```
it('MM-T4291 Group by different property', () => {
    // code
});
```

Note:
1. Use [queries from testing-library](https://testing-library.com/docs/dom-testing-library/api-queries) whenever possible. We share the same philosophy as the [testing-library](https://testing-library.com/) when doing UI automation like "Interact with your app the same way as your users" and so, please follow their guidelines especially when querying an element. 

If you're interested, please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Focalboard" community channel](https://community.mattermost.com/core/channels/focalboard).

For new contributors, please see our [guide](https://github.com/mattermost/focalboard#running-and-testing-the-server).

**Comment by Andrewnt219** [comment]
Hi @saturninoabril, I can help with this.

**Comment by kamre** [comment]
Hi @saturninoabril! I am working on this task and have several notes:
* creating a new empty board described [here](https://automation-test-cases.vercel.app/test/MM-T4274) doesn't work for standalone server because side bar is different one (doesn't have the "+" icon at the top for example), so I am using menu at the bottom
* steps 3 and 4 are not relevant now because adding new property now required selection of the property type before creating it, I have made the changes accordingly
* there is no checkmark in step 5 and this looks like a bug that I have fixed locally
* its not clear why adding new group in step 7 should automatically set this group for the card property, this doesn't work like this currently

Can you comment on this please?

**Comment by saturninoabril** [comment]
Thanks @kamre! @ogi-m, could you please help check with the notes and bug as stated above? Thank in advance!

**Comment by ogi-m** [comment]
The missing checkmark is indeed a bug, thanks for catching that @kamre. I'll file an issue.

As for the final step, you're right, it doesn't make sense. I believe my intent when creating the test case was to create a new card in the column. I've updated the steps accordingly.
