### ISSUE TITLE
Feature Idea: Filter for date properties

### ISSUE THREAD

**Issue by nishantwrp** [mattermost/focalboard#1863]
## Summary

Currently, I can't add a filter in a view for a date property. I think it'd be great if it was possible. I'd like to see cards which are after a particular date or cards that have a date set, etc.

## How important this is to me and why

Importance: Medium

**Comment by CarbonHeartDev** [comment]
I can take care of this

**Comment by CarbonHeartDev** [comment]
I'm working on implementing it

**Comment by CarbonHeartDev** [comment]
I keep working on this issue, I'm still getting my feet wet but I feel which I'm gradually getting accustomed with the project and soon I'll gain enough moment. 
I understood how filters works in Focalboard and now I'm implementing the aforementioned filters for Date properties as written on the issue but I have a doubt: on Focalboard a Date property field can be both a single value and a range and this is making harder for me to decide which filters to implement since filters which works well for single dates not always works well for ranges too, for example an "isAfter" filter makes sense for a single date (property date X is/is not after filter date Y) but not makes much sense for ranges (property range Z is/is not after filter date Y but filter date Y can even be between property range Z initial and final dates and what should I do in that case? Should I filter it or not?).
A list of the filters you'd like to be implemented for Date properties would be very helpful.

**Comment by harshilsharma63** [comment]
cc @wuwinson @asaadmahmood thoughts on how this should work?

**Comment by asaadmahmood** [comment]
@harshilsharma63 @nishantwrp Something as simple as this should work.
![image](https://user-images.githubusercontent.com/11034289/196384370-5ba7eaf0-a502-4d51-9b5f-eaeaa416059e.png)
![image](https://user-images.githubusercontent.com/11034289/196384389-0fbf0e93-4ec3-46a0-962a-0dcc94ef81cf.png)

**Comment by asaadmahmood** [comment]
If we want to do that, we may want to do something like this.
![image](https://user-images.githubusercontent.com/11034289/196391916-42f92115-7d39-4a82-bae0-d23a1dd4fb1c.png)

**Comment by Pinjasaur** [comment]
@CarbonHeartDev I've assigned you to this, please feel free to keep asking questions.

**Comment by wuwinson** [comment]
Relevant tickets for additional reference:
- https://github.com/mattermost/focalboard/issues/1031
- https://github.com/mattermost/focalboard/issues/1431

## Requirements
For any `Date`, `Created time`, or `Last updated time` property selected in the filter dropdown, display the following filter options with a calendar picker to specify the dates:
1. **is** - Only display cards that matches the exact date. For date ranges, both the start and end date must match the date specified.
2. **is before** - Only display cards that have dates before the specified date. For date ranges, use the end date.
3. **is after** - Only display cards that have dates after the specified date. For date ranges, use the end date.
4. **is set** - Only display cards that have any dates on the selected date property.
5. **is not set** - Only display cards that do not have any dates on the selected date property.

**Comment by wuwinson** [comment]
Shipped in v7.8.
