### ISSUE TITLE
Bug: can't open cards on Safari

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#2002]
## Steps to reproduce the behaviour

1. Create new board
2. Try to create new card
3. See empty screen

## Expected behaviour

Card dialog should be visible

## Edition and Platform

 - Edition: Personal Server
 - Version: `0.12.0` on `main` branch
 - Browser and OS: Safari 15.2 on macOS

## Additional context

The issue comes from the `live-markdown-plugin`, in particular the [regexp with lookbehind](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/live-markdown-plugin/inline-styles/italicStyleStrategy.ts#L7) that is [not supported in Safari](https://caniuse.com/js-regexp-lookbehind)

@chenilim FYI

**Comment by chenilim** [comment]
Thanks for filing! Just catching up after the holidays. Confirmed this is an issue with Safari (and likely FireFox) because they [don't support the lookbehind RegEx operator](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group). Working on a fix.
