### ISSUE TITLE
Bug: Unable to run Focalboard Desktop on Linux: unable to open database file: no such file or directory

### ISSUE THREAD

**Issue by eidsheim98** [mattermost/focalboard#2064]
Getting an error when trying to run Focalboard Desktop:
```bash 
ERROR INITIALIZING THE SERVER STORE unable to open database file: no such file or directory
2022/01/07 15:51:21 Failed to start the server
2022/01/07 15:51:21 unable to open database file: no such file or directory
```

## Steps to reproduce the behavior

1.    Download focalboard-linux.tar.gz from the latest release on GitHub
2.    Unpack the .tar.gz archive using 
```bash 
sudo tar -xvf focalboard-linux.tar.gz -C /opt
```

3. Run focalboard-app from /opt/focalboard-app using

```bash 
./focalboard-app
```

## Expected behavior

Focalboard should start

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.11.0 and v0.12.0 - RC1
 - Browser and OS: KDE neon User Edition 5.22 x86_64

**Comment by jespino** [comment]
This looks like a bug, but is not, it is a permissions problem.

Because you execute the `tar -xvf` with `sudo` you are creating the new `/opt/focalboard-app` as a root user, so the owner of the directory is the `root` user. Then, when you try to execute the `./focalboard-app`, it tries to open/create the `focalboard.db` file, and because the regular user doesn't have permission to create files in the directory it fails.

The solution to this would be, to change the owner of the directory to your regular user, or just execute the `tar -xvf` with the regular user and to a place where you have permissions to create the `focalboard-app` directory.
