### ISSUE TITLE
Bug: Comments writes backwards

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2075]
## Steps to reproduce the behavior

1. Go to Comments
2. Enter a comment
3. cursor gets set to beginning
4. Comment writes backwards

## Expected behavior

Comment to be written correctly

## Screenshots
https://user-images.githubusercontent.com/5587620/148599247-d12d2181-fc01-4fe9-a071-f76e7e2e34e1.png

## Edition and Platform

 - Edition: Personal Server
 - Version: Main
 - Browser and OS: [e.g. Chrome 91 on macOS, Edge 93 on Windows]

## Additional context

Caused by https://github.com/mattermost/focalboard/pull/2058

**Comment by kamre** [comment]
@sbishel looks like editing of the text for comments has not been fixed by #2076 

There is additional `onChange` callback in the [comments component](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/cardDetail/commentsList.tsx#L60-L63) and this might be the reason of the difference with [text element component](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/content/textElement.tsx#L24-L32).
