### ISSUE TITLE
Feature Idea: Multi-select person property

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2413]
## Summary

Ability to select more than one user on a person property. Currently, it's only possible to select one user per person property type.

## How important this is to me and why

Importance: Medium

Use cases:
1. Assign multiple people to a task

**Comment by jespino** [comment]
@wuwinson I kinda dissagree with the approach. I think we have multiselect fields and select fields, in the same way we should have something like "multiperson" and "person" fields. Because for example, I can want to strictly have 1 single assignee and maybe multiple "implicated people". I think the 1 only element restriction is an important feature.

**Comment by alerque** [comment]
@jespino As I understood it that's what the original request was for: a multi-select variant of the person field. I don't think anyone was suggesting not having a single select field.

**Comment by wuwinson** [comment]
@alerque @jespino That's correct. I didn't explicitly define the solution here, but the request is to support a multi-select person property. We can keep them as separate properties to stay consistent with our other multi-select field. Didn't realize this was getting worked on already by @Rajat-Dabade, but I can write up a simple spec and share with the team. Thanks!

**Comment by Rajat-Dabade** [comment]
This is been done as a part of this PR: https://github.com/mattermost/focalboard/pull/3741, so closing this issue.
