### ISSUE TITLE
Bug: Resizing a table column is unusably slow

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2442]
## Steps to reproduce the behavior

1. Open a table view
2. Drag to resize the first column (or any column)
3. The live resizing lags and is pretty much unusable

## Expected behavior

Resizing should be fast and easy

## Screenshots

https://user-images.githubusercontent.com/46905241/156465311-83bddc5d-cdb1-4e37-82ba-09740c7a4e7f.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14.0
 - Browser and OS: Chrome on Mac

## Additional context

This may be caused by the live-resizing. Recommend either improving the live-resizing, or replacing it with resize-on-mouse-up.

**Comment by kamre** [comment]
Hi @chenilim I have also noticed this performance problem with resizing column and have already looked in React Dev Tools. 

One of the reasons is that all components inside the table are rerendered on each mouse movement. Another thing is the issue inside `react-dnd` that was recently fixed in this [pull request](https://github.com/react-dnd/react-dnd/pull/3313).

I am going to work further on this issue improving the live-resizing, so you can assign it to me.

**Comment by LimitlessDonald** [comment]
Hello @kamre thanks for your work. Do you think your changes would fix this issue here : https://github.com/mattermost/focalboard/issues/2907 ?

KIndly check thanks .
