### ISSUE TITLE
Bug: AWS builds for Windows10 standalone app is broken

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#2593]
## Steps to reproduce the behavior

1. Download Windows build from https://focalboard-builds.s3.amazonaws.com/latest/focalboard-win.zip
2. Unzip
3. Open `focalboard.exe`
4. Bypass Windows Defender: Select More Info, and select `Run Anyway`
5. App doesn't open

## Expected

App runs. See note below for additional debug info.

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v0.16.0
 - Browser and OS: macOS/Safari & Windows 10/Chrome

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

(Outdated info) Please see conversation in [~focalboard channel](https://community.mattermost.com/core/pl/n3wbwih3bpr9pfhm8ew9wjj79c) for more details.

**Comment by lindy65** [comment]
Hi @chenilim - FYI, this bug is blocking tests from running in Rainforest

**Comment by chenilim** [comment]
Thanks @lindy65. We should triage this today, cc @sbishel, @wuwinson.

**Comment by lindy65** [comment]
Thanks @chenilim :)

**Comment by chenilim** [comment]
@jespino, are there more fixes required for this?

**Comment by lindy65** [comment]
@chenilim - the AWS build for Windows 10 does not open after extracting the files. Double-clicking on "Focalboard.exe" does nothing.

There seem to be a few bugs around Status and adding properties in the AWS build for macOS

![image](https://user-images.githubusercontent.com/13020833/161693810-8b2be2c9-53ee-479b-9ac4-424d463cf132.png)

**Comment by chenilim** [comment]
Thanks @lindy65. Are **both** the Mac and Windows build broken for you? I am able to repro it for Windows. I spent some time debugging, and the error appears to be:
```
2022/04/05 18:23:19 server.NewStore ERROR{error 1 0 0 cannot read migration "000001_init.down.sql": open migrations\000001_init.down.sql: file does not exist <nil>}
```
From what I can tell, the migration system was changed to morph in the permissions branch, and that was when this issue started happening. i.e. it repros on the permissions-branch PR (https://github.com/mattermost/focalboard/pull/2578), but not on the one right before (https://github.com/mattermost/focalboard/pull/2572).

@sbishel, this appears to be a different issue from the menu behavior change, and appears to be related to migrations. Could we get someone to investigate?

BTW, I am seeing some unexpected behavior on the Mac App (since the permissions merge): I can't make any updates but it is able to launch, so might be a different issue. @lindy65, if the Mac App launches for you but breaks elsewhere, could you help file another issue to track that? Thanks.

**Comment by chenilim** [comment]
A couple more data points:
* The same error is shown when I build and try to run `focalboard-server.exe` on Windows.
* We swtiched from using go-migrate to morph in the permissions-branch

**Comment by chenilim** [comment]
@lindy65, I've filed https://github.com/mattermost/focalboard/issues/2731 to track the issue I'm seeing on the Mac App. Please update that if you are seeing different behavior on the test builds. Thanks!

**Comment by lindy65** [comment]
Thanks @chenilim - I'm seeing the same issue on the Mac App where updates are not being saved until after a refresh. I've updated #2731

**Comment by lindy65** [comment]
Hi @chenilim - for the Windows 10 app, it doesn't open at all after installation and there is an error `403 Forbidden` in the js.console

![image](https://user-images.githubusercontent.com/13020833/162690322-3c554ccd-0c4e-4498-bc35-0f1aa4e30d0b.png)

**Comment by chenilim** [comment]
Updated the title of this bug to just focus on the Win10 build issues, which appear to be different from the macOS app issues, tracked by https://github.com/mattermost/focalboard/issues/2731.

**Comment by chenilim** [comment]
Thanks @lindy65, I've updated the repro steps to what I currently see against the latest build, which is consistent with the repro I got previously. Currently, this appears to be an issue with the migrations, which cause a crash in the server and app.
