### ISSUE TITLE
Bug: Guest User can @mention users from other teams

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#2604]
## Steps to reproduce the behavior

1. Create a User in TeamA.
2. Create a guest user and add to TeamB
3. Login as Guest User
4. Go to boards
5. Select a card. Attempt to @mention User in TeamA

## Expected behavior
Guest users should not be able to @mention users in other teams.

**Comment by chenilim** [comment]
Note:
* If a regular (non-guest) user types `@` - they should see the list of all users in the system (across teams)
* If a guest user types `@` - they should see the list of all users in the current team

**Comment by chenilim** [comment]
Reassigning to Winson for the next milestone. Clarify expected behavior wrt notifications, etc.

**Comment by wuwinson** [comment]
In our original [Permissions Phase 2 spec](https://docs.google.com/document/d/1IiIgtXI_lYtTSpm6XfqPvSe_jD0E0rajqerWSRLC6OQ/edit#bookmark=id.rj4ycga2f86), we defined the behavior so that guests can only @mention explicit board members. Now with the addition of [channel permission groups](https://docs.google.com/document/d/1DFteQ7qb3xYY5c4cS1N1LppDffDaJX-MCJZwcMfUSF4/edit?usp=sharing), we can consider expanding this out to explicit board members and any channel permission groups.

**Comment by wuwinson** [comment]
As per the [Confirmation Modal for Non-Members](https://docs.google.com/document/d/1IiIgtXI_lYtTSpm6XfqPvSe_jD0E0rajqerWSRLC6OQ/edit?usp=sharing) spec, guests should only be able to @mention explicit board members and users in the synthetic channel permission groups.

**Comment by Pinjasaur** [comment]
Working on this.
