### ISSUE TITLE
Bug: boards bot shows paragraph characters when posting updates to cards

### ISSUE THREAD

**Issue by matthewbirtch** [mattermost/focalboard#2658]
## Steps to reproduce the behavior

1. Follow a card
2. As user B, make changes to that card that includes line breaks or paragraph breaks
3. As user A, you'll get a notification from the Boards bot
4. Notice there are Paragraph special characters as part of the changes

## Expected behavior
Show the actualy line breaks and paragraph returns rather than the paragraph character

## Screenshots (optional)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/2040554/160480862-96b6141a-7492-4325-9ba5-6eb388e25b93.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/2040554/160480892-cff515bb-8446-4b6b-936c-b2ee018ec592.png">

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition:  Mattermost Boards (plugin)
 - Version: ? (on community-daily)
 - Browser and OS: Desktop app

**Comment by chenilim** [comment]
cc @wiggin77.

**Comment by wiggin77** [comment]
@chenilim this is by design.  Including the line breaks makes a diff an indecipherable mess.  We try to include just enough text to provide context around the change(s), but when that context contains line breaks it becomes confusing.

However, we could make a special case for adding a comment since the diff is really just added content with nothing deleted.

**Comment by chenilim** [comment]
Thanks @wiggin77, that makes sense. +1 for adding a special case for added comments (or additions in general). cc @wuwinson, @asaadmahmood.

**Comment by wuwinson** [comment]
Works for me @wiggin77.
