### ISSUE TITLE
Permissions Branch: Selecting Welcome template does not restart product tour

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2710]
## Steps to reproduce the behavior

1. Go to template picker
2. Select  "Welcome to Boards!" template
3. Welcome board is added to the sidebar, but product tour doesn't start

## Expected behavior
Product tour starts after Welcome board is added to the sidebar

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment]
@wuwinson I tried on the latest `main` and it's working fine. You mentioned `Version: permissions-feature-branch`, regarding that, we're no longer using that branch since we merged it in `main`. May that's the issue? Can you please try on the latest main?

https://user-images.githubusercontent.com/18575143/162125949-b029b4b8-d02e-46b0-a403-45669c3e4b0f.mov

**Comment by wuwinson** [comment]
Thanks @harshilsharma63, closing this out!

**Comment by harshilsharma63** [comment]
@wuwinson that's definitally an old server, @ogi-m do we have a server with `main` deployed on it? If not, @wuwinson you can spin up a new cloud server for this.

**Comment by harshilsharma63** [comment]
@wuwinson did you notice the bug in the latest bugbash? If not, we can close this issue.

**Comment by wuwinson** [comment]
Thanks for the reminder @harshilsharma63! Can't repro in the latest bugbash - closing this one out.
