### ISSUE TITLE
Bug: Text change for Not all team members are listed on the permissions modal search 

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2996]
## Steps to reproduce the behavior

1. Go to board
2. Open the permissions modal
3. Click on the search bar
4. Scroll down to see team members to add to the board
5. See error - only select team members appear on the dropdown

## Expected behavior
Search bar placeholder text should display as "Search for people" - see comments below for context.

## Screenshots (optional)
**List of team members**
![Screen Shot 2022-04-28 at 3 48 48 PM](https://user-images.githubusercontent.com/93531870/165834289-31f97edd-e62a-47e0-aec2-f4970e9580d2.png)

**Members who appear on dropdown**

https://user-images.githubusercontent.com/93531870/165835123-2c22d6ba-e047-4297-ab98-9548f4ce9d03.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash 2)
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
From closed PR for reference - 

@sbishel I think the limit of 10 users was intentional and expected. Depending on the team, it can be a huge list. I think this is actually a UX issue in that it's not communicated to the user that you need to search for the items you're looking for. Happened to me too.

@wuwinson why is it required to show all users in that scrolling dropdown? If we make it more explicit that you need to search for things, would that be fine as well? cc @asaadmahmood 

@wuwinson also, the member's list view in channels you demoed in the video in the issue shows only 100 users max. It feels it's showing all users because there are <100 users on the test server or local server. Try opening that thing for Town Square on community.

The API call used for that list in channels has a hardcoded 100 users limit param being sent, for the same reason we added the 10 user limit in Boards-

```
https://community-daily.mattermost.com/api/v4/users?in_channel=so48j8ynojdtmbr8kdzzpzuztw&page=so48j8ynojdtmbr8kdzzpzuztw&per_page=100&sort=
```

We can certainly increase our limits to match what Channel has but no limits is not a good idea IMO.

I'm 3/5 on keeping the hardcoded 10 users limit.

**Comment by sbishel** [comment]
From closed PR for reference - 
Will discuss with @asaadmahmood @chenilim in our PM/Design meeting this Thursday (May 5th) to figure out some short term and long term solutions to address this. 

- Need to make it clearer to users that they can search for users outside the list of 10 recents displayed. 
- Consider whether we or not we need to increase the limit above 10.
- Pagination is expensive and not recommended for the timebeing.

**Comment by wuwinson** [comment]
@justinegeffen @asaadmahmood Any suggestions on updating the copy here so it's more obvious that it's a search bar? Any objections with simply replacing "Select" with "Search"? ![Screen Shot 2022-07-05 at 4 57 46 PM](https://user-images.githubusercontent.com/93531870/177415516-cca4c967-a184-479b-ac37-4c5ca971dc16.png)

**Comment by justinegeffen** [comment]
How about "Search for people" to match the modal in Channels?

**Comment by wuwinson** [comment]
Sounds good, thanks @justinegeffen!
