### ISSUE TITLE
Bug: Migration error - Container don't start

### ISSUE THREAD

**Issue by Zazou49** [mattermost/focalboard#3210]
## Steps to reproduce the behavior

1. Start container

## Expected behavior

I set up 2 weeks ago a container on unRAID without problem. Today I started the container and error appeared.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/89610869/173136518-c2d08afe-d20e-4513-b836-47fbc93d2891.png)

## Edition and Platform

 - Edition: Personal Server
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

**Comment by avanheuvelen** [comment]
I can reproduce this. It happens every time I update from 0.16.0_6.0.22 to 7.0 on TrueNAS Scale through [TrueCharts](https://github.com/truecharts/apps).

**Comment by avanheuvelen** [comment]
There are some related issues: #3214 #3208

**Comment by wuwinson** [comment]
Thanks for reporting @Zazou49 @avanheuvelen! Unfortunately, `v0.16 RC1` was an interim release that we ended up not shipping, which is why you're running into this issue. Apologies for any confusion that may have caused. We removed that release to prevent others from running into this issue. I've added [this discussion](https://github.com/mattermost/focalboard/discussions/3225) for additional clarity.
