### ISSUE TITLE
Bug: Default task template 

### ISSUE THREAD

**Issue by thomaslc66** [mattermost/focalboard#3275]
## Steps to reproduce the behavior

1. Go to a board that you've previously created
2. Create a new task and add some properties
![image](https://user-images.githubusercontent.com/9827392/175296835-c5baad14-3de8-4c07-aa0b-f64d8f0213a6.png)

3. Save the modification
4. Set this template as "Default"
![image](https://user-images.githubusercontent.com/9827392/175297070-dff9ccff-c502-43dc-8b7d-47b8723c75ff.png)

## Actual behavior

1) if you click on the + New button at the bottom of a column, the default template is not selected
![image](https://user-images.githubusercontent.com/9827392/175297194-e9772dd9-f10e-48a8-864d-6d8cf00420f3.png)

2) if you click on the New button (top right) 
![image](https://user-images.githubusercontent.com/9827392/175297288-6668f99b-a1c0-4150-a444-6cccb7222d77.png)
If you fill the template with your info but for a specific task you don't want (let's say) a "due date" in it and delete this property (in your new task not the template), when you go back to the template edition, the "Due date" property is also delete from the template.

## Expected behavior

1) If I set default template, I should be able to have the default template when I click on all the "New" button and not only the blue one but also the ones under each column

2) Modification on a specific task, should not be reflected in the template.

## Edition and Platform

 - Edition: Personal Server
 - Version: [6.5.1]
 - DB Schema Version: [6.5.1]
 - Database: postgres
 - Browser and OS: Chrome
 
 
 
 Is it something that is fixed in Latest Release: 7.0.0? Didn't see anything in the changelog.
 
 Thank you for the update

**Comment by sbishel** [comment]
For Item 1. The New button at the bottom of a Kanban column should use the template and then apply the proper property for the column.
This will apply to all views. "New" should use template and apply field (as necessary based on view).

Item 2 - Is by design. All cards for a board share columns and deleting a property deletes on all cards. (There is warning message to this effect.)

**Comment by thomaslc66** [comment]
@sbishel Thank you for your answer.

For Item 1. As stated in our tests "New" does not always take the default template.

For Item 2. Makes no sense to have a default template then if all cards share the same properties and that every card can edit the template. Then what happen if I have 2 different template with different properties ? Will the default one delete the properties no existing inside the other one. And also will the modifications in one of my template edit my default template?
That's really weird and I can see no real use case where this is useful. 

It's seems also that you've named if "A template" why name it a template when it's not and it's just a default "Card"?

I'm a bit confused about this.

**Comment by wuwinson** [comment]
@thomaslc66 Thanks for your feedback!

**For item 1:** This is a bug. The blue "New" button on the top right is working as expected. However, as @sbishel mentioned, the "New" buttons under each column on the Kanban view should use the template first and then apply the proper property for the column. Currently, they're not using the template at all, and only applying the property for the column.

**For item 2:** This is the expected behavior, but I understand where the confusion is coming from. The card templates are there to help with efficiency, so you don't have to keep manually populating the same **property values** for certain cards. For example, from your screenshots, you can have different card templates with preset values for `Status`, `Priority`, and `Assignee`, so you don't need to apply those values every time. 

However, because all cards on a board share the same properties - adding or deleting a property will apply to all cards on a board, including the card templates. What we need is a way to hide certain properties from individual cards to address this use case. I filed enhancement idea #3319 so we can keep track of this. Please feel free to add any additional comments to that ticket.

Hope that helps clear things up!
