### ISSUE TITLE
Bug: bugbash 7.2 Team members not appearing in Assignee property dropdown

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3307]
## Steps to reproduce the behavior

1. Create board from RoadMap template (or any template that has Assignee prop or any person property type)
2. Click Share button
3. Set `Everyone at Focalboard Team` to have comment permission
4. Open card
5. Try to set Assignee property
6. Notice only explicit board members are in the dropdown list.

## Expected behavior

Users won't know the difference between implicit and explicit membership.  If they set permissions for all team members they would expect all team members to show up in person lists.

## Edition and Platform

 - Edition: Bugbash 7.2
 - Version: 7.2
 - Browser and OS: FF Linux

**Comment by wuwinson** [comment]
@asaadmahmood Can we get designs for this? Want to show everyone on the team with a divider/indicator for non-explicit board members

**Comment by asaadmahmood** [comment]
@wuwinson We already have a design for that:
https://www.figma.com/file/tBRYmKqR1pUo02EeAHXF2P/Issue-512---User-not-in-Channel%2FBoard?node-id=501%3A24609

**Comment by wuwinson** [comment]
Missed that, thanks @asaadmahmood!

**Comment by wuwinson** [comment]
Spec: https://docs.google.com/document/d/1IiIgtXI_lYtTSpm6XfqPvSe_jD0E0rajqerWSRLC6OQ/edit?usp=sharing

**Comment by jespino** [comment]
I think this is not fixed in main, if you have permissions to manage members of the board you are going to be able to search for users in the team, if not you are not going to be able. Once you choose one of the members, you need to add the member to the board to assign it, if not, you are no going to be able to assign it. Can you confirm that is what you expect @wuwinson ?

**Comment by wuwinson** [comment]
> if you have permissions to manage members of the board you are going to be able to search for users in the team, if not you are not going to be able. Once you choose one of the members, you need to add the member to the board to assign it, if not, you are no going to be able to assign it.

@jespino Yep, this is the expected behavior for a private board. Only board admins will be able to search for users on the team and add them to the board. Everyone else will only see board members on the person property and for @mentions.

For a public board however, an Editor or Commenter can also search for users on the team, and add them to the board as the **default** role. A board Admin on a public board can **specify the role** of the new user when adding them to the board. See the matrix for reference:

![Screen Shot 2022-09-07 at 10 23 57 AM](https://user-images.githubusercontent.com/93531870/188903038-881f303a-89db-4159-b265-f9f6b7cceb7a.png)
