### ISSUE TITLE
Bug: Link with specific characters are double encoded

### ISSUE THREAD

**Issue by roukmoute** [mattermost/focalboard#3496]
## Steps to reproduce the behavior

1. Add a comment on a ticket and add a link with spaces or another custom character.
2. Try with : `https://example.com?title=August 1 - 2022` or `https://example.com?title=August%201%20-%202022`

For the first link, it is cut and it is not possible to use it entirely event if I try to do some markdown.

For the second link, the link is reinterpreted to `https://example.com?title=August%25201%2520-%25202022`.
![image](https://user-images.githubusercontent.com/2140469/182122318-f0a96551-77a8-4b5e-a07d-6a581b081b44.png)

## Expected behavior

If I click I must be able to redirect on the same link.

## Edition and Platform

 - Edition: Focalboard on Unraid
 - Version: 7.1.0
 - Browser and OS: Firefox

**Comment by chenilim** [comment]
@wuwinson, please investigate the expected behavior. Thanks.

**Comment by sbishel** [comment]
This can be fixed by unencoding, then encoding.

**Comment by wuwinson** [comment]
Expected behavior:
1. `https://example.com?title=August 1 - 2022` should take user to URL prior to any spacing, in this case it should direct user to `https://example.com?title=August`
2. `https://example.com?title=August%201%20-%202022` should not encode the '%', and instead direct user to the URL as is.

**Comment by roukmoute** [comment]
3: In a markdown link, `1.` must be encoded correctly
