### ISSUE TITLE
Bug: Can't search for an untitled board

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3542]
## Steps to reproduce the behavior

1. Create an untitled board
2. Open the Boards Switcher (Ctrl/Cmd + K)
3. Try searching for `(Untitled Board)` as displayed in UI
4. See no results

## Expected behavior

Able to search for untitled board(s).

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/6335792/182726552-f42008c3-9b75-41bb-a524-7ef63e1532ec.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2
 - Browser and OS: FF103 Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by Pinjasaur** [comment]
I noticed this while trying to repro #3530. @wuwinson do you know if this behavior is intended?

**Comment by wuwinson** [comment]
No, any board with the words "untitled" should appear in the search results.

**Comment by sbishel** [comment]
A board that displays "(Untitled Board)" does not have a title. (ie. title = "")(empty string). So without some fancy conversion in order to search for "", this can't work and shouldn't be fixed.

That said...we should not allow a board with a blank title be saved or save a new board with a default title "Untitled Board".  Rather than "". Untitled Boards are a mistake, there is no reason to have a board without a title. So lets not allow it. Those that exist should be deleted or given a title. But I wouldn't spend the time "making them work."

**Comment by Pinjasaur** [comment]
Yeah, I was thinking the same thing—the `(Default Board)` i18n happens on the frontend and the search query happens on the backend.

**Comment by wuwinson** [comment]
We should consider implementing @sbishel suggestion on enforcing names for empty boards/templates to avoid this issue. Closing this one out as won't fix for now until we can address Scott's suggestion in the future.
