### ISSUE TITLE
Bug: Cannot create explicit membership for implicit member

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#3808]
## Steps to reproduce the behavior

1. Create a board with a channel association. 
2. In share dialog, attempt to find a member of the channel 
3. Channel members are not displayed, so you cannot choose one.

## Expected behavior

Channel members should be available to create explicit membership.

## Screenshots (optional)
<img width="625" alt="Screen Shot 2022-09-08 at 12 26 10 PM" src="https://user-images.githubusercontent.com/12704875/189197947-b8ba93c6-54ca-4c90-810a-056cf17d535c.png">
<img width="619" alt="Screen Shot 2022-09-08 at 12 28 16 PM" src="https://user-images.githubusercontent.com/12704875/189198374-299891d9-a356-4271-9d18-ef0b051dc318.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3.0-rc1
 - Browser and OS: [Chrome on Mac]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 2: Affects major functionality with a difficult or non-obvious workaround

**Comment by Pinjasaur** [comment]
I'll need to dig in a bit more but I _think_ the problem is they're being filtered out because they're already showing up as board members (because they're implicit through the channel<>board association).

https://github.com/mattermost/focalboard/blob/ed655ac996fd39327c01e288b8dcecb649aae73c/webapp/src/components/shareBoard/shareBoard.tsx#L363
