### ISSUE TITLE
Bug: Follow button and options menu is repositioned and cut off

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3813]
## Steps to reproduce the behavior

1. Go to a card
2. Click on options menu
3. See error - menu is cutoff

## Expected behavior

Options menu is fully visible. @asaadmahmood Confirming again - is "Follow" button intentionally repositioned to the left now?

## Screenshots (optional)

![Screen Shot 2022-09-08 at 2 47 04 PM](https://user-images.githubusercontent.com/93531870/189203677-1c511f5d-c33a-4da6-acbb-af30fdef0c16.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 RC1
 - Browser and OS: Chrome on Mac

**Comment by lindy65** [comment]
Adding here that the menu being cut off also reproduces when creating a template from a card then clicking on the 3-dot menu from within the template

![image](https://user-images.githubusercontent.com/13020833/189498964-879e4859-dce5-4475-b95c-403765a184ff.png)

This issue was found by a QA community contributor and I also reproduced on the https://boards-bugbash73.test.mattermost.cloud/ server.
