### ISSUE TITLE
Bug: Linked board keeps redirecting to an error page

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3815]
## Steps to reproduce the behavior

1. Open Boards RHS from a channel
2. Click on a linked board
3. The linked board opens on a new tab
4. From the same tab, open another board on your sidebar
5. Go back to the channels tab
6. Click on the same linked board from step 2
7. See error

## Expected behavior

The board you clicked on opens in a new tab.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/192799514-6bf0ebeb-be33-4a52-a18e-446e3d7d7c4f.mov

![image](https://user-images.githubusercontent.com/93531870/192841667-94d4eca0-da25-4572-ac94-9aceac13919d.png)

![image](https://user-images.githubusercontent.com/93531870/189235997-d9ec6edd-cca8-40d9-92ff-d9d9a1596275.png)

![image](https://user-images.githubusercontent.com/93531870/189236031-3cc6ed14-5ffc-4d9f-b645-6e83963cd4b9.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.1 on Community
 - Browser and OS: MM Desktop app and Chrome on Mac

**Comment by wuwinson** [comment]
@harshilsharma63 Might have to work with SRE to get error and/or database info. cc @sbishel @ogi-m

**Comment by wuwinson** [comment]
@harshilsharma63 Still waiting to get more details from @amynicol1985. Please hold off on this one for now. Thanks!

**Comment by wuwinson** [comment]
@amynicol1985 Are you still able to repro this issue? Can you share a screen recording with us if so? Thanks!

**Comment by sbishel** [comment]
I dug into this base on this [conversation](https://community.mattermost.com/private-core/pl/ku8d1kbnotgptcxrf1srp1rnpe). 

There are a few different things going on here that will take a while to unpack. But, it essentially goes back to the board not having a select property. 
<img width="1483" alt="Screen Shot 2022-09-28 at 12 07 20 PM" src="https://user-images.githubusercontent.com/12704875/192856572-620995fa-9074-44c7-b7a3-18917e98a319.png">

Even though there is no Kanban view, under certain circumstances, it attempts to load one (still working on identifying why), which fails because of lack of select property. 

Then we throw it into an error loop by attempting to navigate to `plugins/focalboard/error?id=unknown`, but actually navigate to `https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/plugins/focalboard/error?id=unknown` which starts the whole round of error looping.
