### ISSUE TITLE
Bug: Viewers and Commenters see IDs on empty person property

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3951]
## Steps to reproduce the behavior

1. Go to a board as a Viewer or Commenter
2. Open a card with an empty person property
3. See error - some type of user ID is displayed even though the property is empty
4. Switch role to Editor or Admin and the person property correctly displays as empty

## Expected behavior

Person property correctly displays as empty.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/194377852-780e4d1d-25dd-4aed-aaf2-9f3629c61b0f.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by sbishel** [comment]
I don't believe this is an issue. A read-only user will simply display the text, which would be a GUID in the case of a user field. The editor and admin are not displaying because the User no longer exists. 

The large issue is to display User Names in Readonly. There is already a ticket on this. Closing
