### ISSUE TITLE
Bug: Autocomplete does not appear when @mentioning more than one user is the same comment

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#3975]
## Steps to reproduce the behavior

1. Go to comments section on a card
2. @mention multiple people on the card
3. See error - autocomplete only appears for the first user but not the other users

## Expected behavior

Autocomplete displays whenever an @ is typed into the card comment or description

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/194608679-77c99829-18b5-4f8c-881f-16cba8bd85b6.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.4.1 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by chirag-ghosh** [comment]
I can work on this

**Comment by wuwinson** [comment]
Thanks @chirag-ghosh!

**Comment by chirag-ghosh** [comment]
OK so I tried debugging this issue. Turns out when I try to mention the second time, the `isMentionPopoverOpen` state, first changes to true and then immediately changes to false.
This issue doesn't happen for the first time. Additionally this issue never occurs when mentioning in the card content.

P.S. Suppose when mentioning for the second time in the comment, we type `@`, then click somewhere outside the input. then when we again click on the input, the dropdown appears.

Other than these observations, I am not able to figure out what might be the issue. Can anybody help out ?

**Comment by wiggin77** [comment]
> the isMentionPopoverOpen state, first changes to true and then immediately changes to false.

@chirag-ghosh I'm not familiar with that specific code, however there would be a handler for keyboard events that looks for `@` keystroke and sets the state.  There may be logic there that checks if the caret is directly to the right of the `@` but the logic may find the position of only the first `@` and assume the caret is not beside a `@`.

**Comment by harshilsharma63** [comment]
@wuwinson it seems to be working fine now for both comments and description-

@ogi-m can you test this please?

Uploading at-mention.mp4…

**Comment by wuwinson** [comment]
Looks to be working now, closing out as `Cannot reproduce`.
