### ISSUE TITLE
Bug: Impossible to register another account

### ISSUE THREAD

**Issue by JamesDAdams** [mattermost/focalboard#3997]
## Steps to reproduce the behavior

1. Go to share a board
2. copy the link
3. try to register with the link

## Expected behavior

I want register with the link

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/20860324/195156128-a295858b-4a40-4c52-a09b-465598645ba2.png)

## Edition and Platform

 - Edition: Personal Server 
 - Version: 7.4.1 docker
 - Browser and OS: Chrome & windows 11

**Comment by JamesDAdams** [comment]
up

**Comment by wuwinson** [comment]
@JamesDAdams Can you share any log errors as well? Thanks!

Potentially related to https://github.com/mattermost/focalboard/issues/4000 - will circle to see if that PR fixes this issue as well. cc @sbishel

**Comment by sbishel** [comment]
Hi @JamesDAdams - Sorry for delay, but I was unable to register an initial user due to #4000. Once that has fixed, I was unable to duplicate your issue. However, after re-reading, I'm wondering if you're actually missing a step...Inviting Users.

Before sharing the board in you're first step - `1. Go to share a board`

You should invite users to register using this link. 
1. Go to to "Focalboard" in the left sidebar
2. Select "Invite Users"

You should see a form as 
<img width="464" alt="Screen Shot 2022-10-20 at 5 18 48 PM" src="https://user-images.githubusercontent.com/12704875/197077039-85f7efd7-3a30-40e2-922c-fc8cf8e527c4.png">

Once registered, the user should then be able to use the share board link.

**Comment by wuwinson** [comment]
Closing out, feel free to re-open if you're still having issues @JamesDAdams!

**Comment by nahoj** [comment]
Thank you @sbishel! It's a bit confusing that there are 2 type of invite links, one to register to Focalboard and one to access the dashboard.
