### ISSUE TITLE
Doc: Microsoft Store version is different from the latest release here. How can I manualy upgrade keeping my board? 

### ISSUE THREAD

**Issue by gowcoizer** [mattermost/focalboard#4003]
Installed the app on Windows 11 from the Microsoft Store, creating account isn't working so I checked latest downloadable version here (focalboard-win.zip)  and it is different. Can I manually update and keep the board I have created so far? Tried with Notepad++ to find where is stored my new data but couldn't find so clarify if possible.

Microsoft Store
![image](https://user-images.githubusercontent.com/36004727/195337778-6788c69e-df97-42e5-b45f-780650648b56.png)

focalboard-win.zip v7.4.1
![image](https://user-images.githubusercontent.com/36004727/195337822-047d9d68-64ba-4cbd-bef0-fc01687d4467.png)

**Comment by DisColow** [comment]
i believe that the personal desktop application doesn't require account creation.
so there should be your bug.

**Comment by wuwinson** [comment]
@gowcoizer To get the latest features on Boards, we recommend switching over to our free [Cloud Starter](https://mattermost.com/pricing/) edition which gives you access to the latest features on Boards, Channels, Playbooks and more.

Microsoft Windows Store shouldn't require an account to download, and the version from Windows Store and the "latest" version from Github are more or less the same. Even though the Windows file on Github is packaged in with the most recent release, we have not updated it since March. If you're having trouble downloading the Personal Desktop edition from the Microsoft Windows Store, then you can absolutely download the Windows version on Github.

Please note the data is stored in different locations from the Windows Store version and Windows local build. See [here](https://github.com/mattermost/focalboard/discussions/2169) for details, so you'd need to export your boards from the Microsoft Store version and import it to the Windows local build version to maintain your current boards.

Check our help docs for more details on [how to export/import boards](https://docs.mattermost.com/boards/migrate-to-boards.html#import-and-export-a-board-archive).
