### ISSUE TITLE
Add Cypress tests: Login actions

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#42]
Simulate user creation, login, and logout actions
* Register user
* Login
* Change password
* Logout

**Comment by djanda97** [comment]
Hi @chenilim! I’m excited to see that Mattermost is working on an alternative to Trello. Once I get the dev environment setup, I’ll take a shot at this issue.

**Comment by jespino** [comment]
Great! thanks @djanda97!

**Comment by kamre** [comment]
@chenilim @jespino I have started working on this and encountered the problem with user registration when _single user_ option is enabled.

In particular [this code](https://github.com/mattermost/focalboard/blob/main/server/api/auth.go#L230-L234) doesn't allow to process user registration.

Do we really need to use _single user_ for cypress testing?

**Comment by kamre** [comment]
As [discussed in focalboard channel](https://community.mattermost.com/core/pl/iy18wtin5p8hjr7eousthuxnkw) this issue is on hold until there is "base Cypress setup with convenient UI and API commands that will make user registration/logging easier"

[My branch](https://github.com/kamre/focalboard/pull/1/files#diff-4b5c671a5f23aabe1811d05711075551cb555074a50d99ae91061e62e0f7f1e6) with Cypress tests can be helpful later.
