### ISSUE TITLE
Bug: Text and placeholder text on cards are center aligned

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4332]
## Steps to reproduce the behavior

1. Go to Welcome template or any other template
2. Open a card
3. See error - card content and placeholder text in properties and comments are center aligned

## Expected behavior

Text should be left aligned

## Screenshots (optional)

![Screen Shot 2022-12-13 at 4 37 50 PM](https://user-images.githubusercontent.com/93531870/207449706-ecdb8c4c-e643-4e91-a5a2-d8180089c262.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5.4
 - Browser and OS: Chrome on Mac
 - [mattermost-server master with MySQL](https://sbishel-master.test.mattermost.cloud/boards/team/5sc6ey6j7f8n8dozkcaq8j9q3h/bhf3sdcjmsjn3ifkythozc4hoxr/vk5guubgrqjnkidphcqg3ypwknr)

**Comment by sbishel** [comment]
This change has caused this issue. https://github.com/mattermost/mattermost-webapp/blob/ab12d0d0708337bee4cfdff35d125734fd61afed/components/air_gapped_self_hosted_purchase_modal/content.scss

We are inheriting this setting which was recently added.

**Comment by sbishel** [comment]
@asaadmahmood - This is being caused by a completely unrelated css change somewhere else in the product. How should we be protecting ourselves against these types of css issues.

**Comment by asaadmahmood** [comment]
@sbishel We can be more specific in our css naming convention.
The `.content` modification introduced in that PR should ideally be more specific, because that's a very basic name for content, but if they're not going to make it specific, we should make our css take precedence.
And we can do that by not using common names like "content" or "wrapper" or etc and have an actual name that's representative of the content.

Generally however, we can't avoid it if base classes like that or base elements are targetted by other products.

I.e.

Imagine a lot of elements in boards and other products are inheriting the base styling from the `body` tag.

If someone on the webapp or any other team goes and adds some stuff directly to the `body` tag and if boards don't have an override set, that will apply to boards as well.

And there are hundereds of css rules that we can't realistically override for each particular tag, so it's a larger suite wide problem that we have to talk about with devs in general.
