### ISSUE TITLE
Bug: board shared with a team, but users in team are listed as “not board members”

### ISSUE THREAD

**Issue by d1nuc0m** [mattermost/focalboard#4376]
## Steps to reproduce the behavior

-  Create a new board
-  Share it, setting all users in a team as editors
-  Create a new task and try to assign it to {user} that is in the team
-  The user is listed as “not board member”, _Add {user} to board_ popup appears, reporting that _{user} is not a member of the board, and will not receive any notifications about it. Do you want to add {user} to the board?_

## Expected behavior

User is listed as a board member and it is possible to assign them a task

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: focalboard - 7.5.1 (on Mattermost Team Edition 7.5.1)
 - Browser and OS: browser and OS independent

## Additional context

Severity:
- Sev 2: Affects major functionality with a difficult or non-obvious workaround

Workaround: 
- Manually add each user to the board. Easy but extremely time consuming with bigger teams and multiple boards.

**Comment by wuwinson** [comment]
@d1nuc0m Thanks for reporting this. This is actually expected behavior to match the experience of a public channel in Mattermost. The [team role](https://docs.mattermost.com/boards/share-and-collaborate.html#manage-team-access) establishes the minimum role for the board, but users still have to search and join the board. Users are not automatically added to every team board, which reduces clutter on their sidebar, and also allows them access to the board when they need it. Once a user opens a board with team access, they will then become an explicit member of the board.

However, I can see how this can be misleading with the UI, so we may need to consider making some adjustments to the Share dialog.

For your specific use case, I'd recommend [linking the board to a channel](https://docs.mattermost.com/boards/navigate-boards.html#link-a-board-to-a-channel) or [adding a public channel to your board](https://docs.mattermost.com/boards/share-and-collaborate.html#channel-role-groups), such as the `Town Square` or `Off-Topic` channel where everyone is a channel member by default. This will effectively give everyone on the team membership to your board. You'll then be able to assign team members on tasks without needing to add them to the board first.

Hope that helps, but let us know if you have any questions. Thanks!

**Comment by d1nuc0m** [comment]
> However, I can see how this can be misleading with the UI, so we may need to consider making some adjustments to the Share dialog.

Yes, probably I'm not the only one that finds it misleading, as [I was told on the forum](https://forum.mattermost.com/t/board-shared-with-a-team-but-users-are-listed-as-not-board-members/14661/3) to report this as an issue

> For your specific use case, I'd recommend [linking the board to a channel](https://docs.mattermost.com/boards/navigate-boards.html#link-a-board-to-a-channel) or [adding a public channel to your board](https://docs.mattermost.com/boards/share-and-collaborate.html#channel-role-groups), such as the `Town Square` or `Off-Topic` channel where everyone is a channel member by default. This will effectively give everyone on the team membership to your board. You'll then be able to assign team members on tasks without needing to add them to the board first.

Thank you, I will try

**Comment by wuwinson** [comment]
Thanks for the feedback @d1nuc0m! We'll start tracking https://github.com/mattermost/focalboard/issues/4459 as an enhancement idea.

**Comment by d1nuc0m** [comment]
> Thanks for the feedback @d1nuc0m! We'll start tracking #4459 as an enhancement idea.

Thank you for the interest
