### ISSUE TITLE
Bug: Board Not Added to Sidebar

### ISSUE THREAD

**Issue by mbauster** [mattermost/focalboard#4423]
## Steps to reproduce the behavior
1. Go to a private Channel with a linked Board that someone else made and linked to the Channel and shared (This bug could also be related to them putting the board they created under a new category other than the default 'Boards' before linking/sharing)
2. Select  Boards
3. The board that I have access to is not showed in the Boards sidebar under the default boards category (or any category for that matter).  It is never added to the sidebar.  The only way to get to the board is from the linked board in the Channel or by searching for the board every time.

## Expected behavior
All boards that I have access to should automatically be added under the default Boards category on the boards sidebar.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop
 - Version:7.5.1
 - Browser and OS: Chrome and Edge on Windows

## Additional context (optional)
Some boards seem to add to the sidebar.  Like the default ones Roadmap or Welcome to Boards.  I can hide them and then search for them and they will re-add.

I got the board to add to the sidebar by asking the creator to move the board back under their 'Boards' category and they added my name specifically as an Editor of the board (even though the whole channel that I am a part of was already added as an editor).  Not sure which of these things was the workaround, but I can see the board in my sidebar now.

**Comment by sbishel** [comment]
@harshilsharma63 - Based on version 7.5.1, I'm guessing this has been fixed. Could you take a look and reference the PR that fixed this, if possible and easy.

**Comment by KOliver94** [comment]
Hi @sbishel,

We have similar issue on our Mattermost instance with both Focalboard version 7.5.1 and 7.5.4. Some boards are public to the whole team, I can search for them and open but I can't do anything to make them appear on the sidebar.

**Comment by wuwinson** [comment]
@harshilsharma63 Can you confirm if this was fixed? Thanks!

**Comment by harshilsharma63** [comment]
@mbauster 

>  The only way to get to the board is from the linked board in the Channel or by searching for the board every time.

This is the only bug - an opened board not being persisted in the sidebar. This has been fixed on `main` branch and would be released in 7.7.

Regarding the expected behavior-

> All boards that I have access to should automatically be added under the default Boards category on the boards sidebar.

We have intentionally prevented this from happening. It sounds something that should bug if I link a few boards in a few channels and you were in those few channels, you'd end up with a lot of board in your sidebar that you may or may not actually need. So instead of forcefully presenting boards to users and asking them to hide it if they don't want access, we implemented the opposite - a board that the user opens, or a board that the user was explicitly granted access to, shows up in the sidebar.

>  got the board to add to the sidebar by asking the creator to move the board back under their 'Boards' category and they added my name specifically as an Editor of the board (even though the whole channel that I am a part of was already added as an editor). Not sure which of these things was the workaround, but I can see the board in my sidebar now.

Them adding your name as the editor made the board show up in the sidebar, like I said above - the board, where you are explicitly granted access, shows up in the sidebar.

Categories is a per-user level concept. It doesn't matter what category a board belongs to for a user and it has no effect on the board's access for another user. Categories are just mapping of user ID - board ID - category ID.

**Comment by KOliver94** [comment]
I can confirm it's fixed on version 7.7.0.

**Comment by harshilsharma63** [comment]
> I can confirm it's fixed on version 7.7.0.

Awesome! Thanks for trying it our @KOliver94 !

**Comment by harshilsharma63** [comment]
@sbishel closing this as its fixed in 7.7.
