### ISSUE TITLE
Bug: Difficulty accessing the board I just created

### ISSUE THREAD

**Issue by amyblais** [mattermost/focalboard#4441]
Original report: https://mattermost.atlassian.net/browse/MM-49532

When i click on the linked board in the channel i get this 404 message in a black popout window

<img width="1019" alt="Screen Shot 2023-01-06 at 2 36 01 PM" src="https://user-images.githubusercontent.com/29708087/211336836-b9116d42-2e38-40c6-ae85-14095d493090.png">

**Comment by sbishel** [comment]
There are two issues here that need fixed. This is due to running in ProductMode. Since we are running in Product mode the plugin path no longer exists (is being created.)

`http://localhost:8065/plugins/focalboard/team/w6br7eb94jgrxpg7iobhrg56jy/b9oe5wbwjni8rud6qw1tgrg9dae`

There should be two fixes made - 
Focalboard, should build these links using the "boards" product path [here.](https://github.com/mattermost/focalboard/blob/main/mattermost-plugin/server/boards/boardsapp_util.go#L84)

Also, I believe the Channels Product should redirect "/plugins/focalboard" to "/boards", since these paths have been used in the past for some time.

**Comment by sbishel** [comment]
The first fix was made, but apparently the second fix isn't necessary per @wiggin77.
