### ISSUE TITLE
Bug: Focalboards disappeared after change of site URL

### ISSUE THREAD

**Issue by XXFOGS** [mattermost/focalboard#4650]
## Steps to reproduce the behavior

1. Go to the admin console
2. Change the web server URL
3. Save it, restart mattermost
4. Lose the ability to access boards

## Expected behavior

Focalboard should be accessible.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/103338067/226213766-f32efc1a-67fe-4002-9457-69f6c71e270d.png)
![image](https://user-images.githubusercontent.com/103338067/226213786-540162cf-0bd9-447c-a983-0146ba89fa49.png)
![image](https://user-images.githubusercontent.com/103338067/226213839-5ecfb4a1-7abf-4fff-97a4-432686e61800.png)
![image](https://user-images.githubusercontent.com/103338067/226213868-b778fbe5-b004-46e9-94ab-11d29593b32f.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.8.3
 - Browser and OS: Mattermost Client (Chromium), Windows 10

## Additional context (optional)

Focalboard database entries are still present in the MySQL database.

**Comment by XXFOGS** [comment]
Update, after further investigation and attempt to reinstall focal board plugin I noticed that its asking for a non-existent table column

![image](https://user-images.githubusercontent.com/103338067/226215086-55a0e279-7117-4b0d-9685-91b42a75fc05.png)

**Comment by XXFOGS** [comment]
### Update

The reason for this bug seems to be the newest focalboard version. Reinstallation and downgrading to 7.8.2 has resolved all issues.

**Comment by sbishel** [comment]
@XXFOGS - What error did you receive when upgrading to `v7.8.3`.

**Comment by sbishel** [comment]
No migrations should even run from `v7.8.2` -> `v7.8.3`. I think that error is probably coming from a `v7.0.1` plugin that is getting loaded. I would suggest completely removing the Boards plugin. I would then upload and install `v7.8.2`, since we know that it works from [here](https://github.com/mattermost/focalboard/releases/tag/v7.8.2). Then you should be able to upgrade to `v7.8.3`. 

I'm assuming your mattermost version is `v7.8.x`. 

@mgdelacroix - Any other suggestions?

**Comment by mgdelacroix** [comment]
@sbishel I agree, an older version running seems to be the cause as the query for `dirty` comes from `golang-migrate`, which we don't bundle on `v7.8.x` but we do on `v7.0.x`
