### ISSUE TITLE
Bug: Tab header displays "OCTO"

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#480]
**Summary:**
When creating and immediately deleting a board template. The tab name displays "OCTO".  

**Steps to reproduce the behavior:**
1. Go to "Add Board"
2. Click on "New Template"
3. Click on "Add Board"
4. Click on '...' next to new board
5. Select "Delete"
6. Placed on Empty page and "Tab" heading is "OCTO"

**Expected behavior:**
Eventually, this should display the "Personal Page", but until then, tab should probably display "Focalboard"

**Screenshots:**
![Screen Shot 2021-05-25 at 3 00 40 PM](https://user-images.githubusercontent.com/12704875/119567816-fe43bd00-bd69-11eb-8a32-2f04f6b9b3d0.png)

**Platform:**
 - Browser and version: [e.g. Chrome 90]
 - OS and version: [macOS 11.3.1]

**Comment by chenilim** [comment]
Ha, yeah this should be an easy search-and-replace fix. :) Setting it as up-for-grabs if someone wants to do that before we triage it next week. Let's just change the default tab name to "Focalboard" for now.

A bit of trivia: OCTO stands for "Office of the CTO", which was @coreyhulen's team that sponsored the initial investigation into what became Focalboard. That's why you'll see octo sprinkled all over the code and CSS properties. Now you know. :)

**Comment by Aashimalik** [comment]
Hi @chenilim,
I would love to work on this.

**Comment by chenilim** [comment]
Thanks @Aashimalik!
