### ISSUE TITLE
Bug: Board name does not show users who have not accessed Focalboard

### ISSUE THREAD

**Issue by jprusch** [mattermost/focalboard#580]
**Summary:**
When opening a board on a direct message or group channel the board name is created by using the user name(s) without any spaces between the names, if more than one user belongs to the channel.

**Steps to reproduce the behavior:**
1. Open a board on a group channel

**Expected behavior:**
The board should be named by using the nicknames oder alternatively the username, but all names should be separated by comma.

**Observed behavior:**
All usernames are concatenated, a comma is generated at the start of the board name. The screenshot shows a board of a group channel with users ma, bar, tr and rs. We could live with ma, bar, tr, rs , but would prefer to use the nicknames.

**Screenshots:**
![image](https://user-images.githubusercontent.com/9337414/122042264-37f06c80-cdda-11eb-9f35-434d6d866ad1.png)

**Platform:**
 - Desktop App Windows 4.7
 - Mattermost 5.36.0
 - Focalboard Plugin 0.6.7 beta
 - OS and version: Windows 10

**Comment by chenilim** [comment]
Thanks @jprusch! @jespino, I think the issue here is that Focalboard only displays the names of users **who have accessed Focalboard at least once**, per the [code here](https://github.com/mattermost/focalboard/blob/main/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L203). I believe you were refactoring this, so assigning to you (please reassign as needed). Thanks.

The desired behavior here is to show the user IDs / usernames even for users who have not accessed Focalboard.

**Comment by jprusch** [comment]
@chenilim I‘m not sure, if this is the cause. I was the only user accessing the board opened from a group channel. All user names of the group are concatenated with a single leading comma.

**Comment by jespino** [comment]
@chenilim yes, I can take care of this.

**Comment by jespino** [comment]
I fixed this in the `main` branch. The usage of `Nickname` is an opinion, it should (in the future) use the users preferences to show DMs/GMs names, and replicate that logic there.

**Comment by jespino** [comment]
I going to close this and create a new enhancement with the names of the board.
