### ISSUE TITLE
Bug: Title is cutoff when viewing a card

### ISSUE THREAD

**Issue by marianunez** [mattermost/focalboard#654]
**Summary:**
When you open a card, the title is cutoff and cannot see the complete contents. 

<img width="839" alt="Screen Shot 2021-06-29 at 4 11 57 PM" src="https://user-images.githubusercontent.com/936315/123861199-e6290580-d8f4-11eb-8aa3-4a1fd2f59f7f.png">

**Steps to reproduce the behavior:**
1. Create a card with a long enough title.
2. Open the card.

**Expected behavior:**
The title should be completely readable like all the other fields in the card. 

**Platform:**
 - Browser: Chrome

**Comment by eduardomota** [comment]
Hi @marianunez, 

when you hover over the title you have a tooltip that shows the whole string, also when you click to "edit" you can see the whole title, at first glance it may help if within the stylesheets is added a `width: 100%;` property to the `.title` class. On a opinion side of this i would say keep your titles short and comment inside with more information, instead of "Complete development ...." (which is subintended) make it "1st iteration..." only.

Cheers

**Comment by mkraft** [comment]
I'm finding this is a usability blocker. In my opinion a detailed view—like you see when you open (rather than list) a card—should show the full details of text fields within reason, with an expand or scroll possibility at an upper bound. Tooltips aren't the greatest usability because they're small, slow to open, and unintuitive.

**Comment by eduardomota** [comment]
@mkraft I've taken the liberty of looking at the code and the title uses an `input` tag that in itself doesn't allow multiline to be able to see the full length of the card. There's the `textarea` tag that will allow that but maybe break some of the functionality to edit and view the label accordingly.

Possible solution:
1. Replace `input` tag with `textarea`
2. Style new tag accordingly

**Comment by jespino** [comment]
This is already fix in the main branch.
