### ISSUE TITLE
Bug: Auto-size Columns with sort arrow

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#692]
**Summary:**
Auto Size does not take the sort arrow into account in the column header.

**Steps to reproduce the behavior:**
1. Create a new Roadmap board.
2. The initial board should display a board with a Priority column header truncated to Priorit...
3. Double click the resize handle on the right side of the Priority column
4. Priority column is still trucated.

**Expected behavior:**
Column header should not be truncated, but display the full column header.

If you remove the sort, you will see it sized correctly without the sort arrow.

**Screenshots:**
![Screen Shot 2021-07-08 at 9 57 20 AM](https://user-images.githubusercontent.com/12704875/124954031-e8fdb780-dfd2-11eb-89e0-0f5878334b46.png)

**Platform:**
 - Browser and version: [Chrome 91.0.4472.114 ,]
 - OS and version: [macOS 11.4]

**Additional context:**

**Comment by nishit-prasad** [comment]
Hello, I'm new and would like to contribute. Can this be assigned to me?

I believe I need to follow the instructions in the below link to setup my environment?
https://www.focalboard.com/contribute/getting-started/dev-tips/

**Comment by sbishel** [comment]
@nishit-prasad Absolutely. And yes those are the instructions to get you started. 
Ask in the [focalboard](https://community.mattermost.com/core/channels/focalboard) channel if you run into issues.

**Comment by nishit-prasad** [comment]
Thank you!

Update:
- Spent few hours on it and turns out that when the doubleClick event fires up, the reference of the header column DOM (such as Priority) is being sent as null to the method that does the auto-resizing.
- But even if I give the right reference of this div element, I see no change in resizing.

Will dig more into it.

**Comment by kamre** [comment]
@sbishel @nishit-prasad after looking in the debugger it seems that [computation of the padding for children](https://github.com/mattermost/focalboard/blob/main/webapp/src/utils.ts#L83-L100) _doesn't take into account sort arrows_ because they are [svg elements](https://github.com/mattermost/focalboard/blob/main/webapp/src/widgets/icons/sortUp.tsx#L10-L17) and their `className` will return a special instance of `SVGAnimatedString` which is processed inside `default` case of the `switch`.

We can skip traversing `svg` elements recursively, which doesn't make sense, and just take into account their `clientWidth` and computed horizontal padding. Something like this:
```js
                if (element.tagName === 'svg') {
                    // no need to traverse svn elements
                    myResults.padding += element.clientWidth
                } else {
                    const childResults = Utils.getFontAndPaddingFromChildren(element.children, myResults.padding)
                    if (childResults.fontDescriptor !== '') {
                        myResults.fontDescriptor = childResults.fontDescriptor
                        myResults.padding = childResults.padding
                    }
                }
```

**Comment by nishit-prasad** [comment]
Ah okay. No wonder when I give the right reference of the DOM to the auto-size method - it doesn't change the `clientWidth`.
Thanks @kamre. Let me play around based on your suggestion and will get back here with further update, as applicable.
