### ISSUE TITLE
Bug: Focalboard plugin v0.8.0 RC1 doesn't load

### ISSUE THREAD

**Issue by eyebank** [mattermost/focalboard#704]
I seem to have an issue with v0.8.0 RC1. When I apply this new code over 0.7.3 and then launch FB I receive a "500 internal server error"
Here is the url: https://XXXXXXXX/plugins/focalboard/workspace/plugins/focalboard/error?id=no_workspace

I am able to downgrade back to 0.7.3 no problem (E10/On-Prem).

**Comment by chenilim** [comment]
Thanks @eyebank! Looks like 0.8.0 requires Mattermost v5.37 due to the new DB connection system ([PR-619](https://github.com/mattermost/focalboard/pull/619)). I've made a note in the release notes.

[Mattermost 5.37 RC1](https://community.mattermost.com/core/pl/myuumxjyg7nqpx3utmbb9bnmwe) released yesterday.

I've confirmed that Focalboard plugin 0.8.0 works against Mattermost 5.37 RC1, and I've updated the min_server_version in the plugin manifest.
