### ISSUE TITLE
Bug: Invite users dialog is cut off by sidebar

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#744]
**Steps to reproduce the behavior:**
1. Click on Focalboard logo to open menu
2. Select Invite Users
3. Invite users dialog is cut off on the right

**Expected behavior:**
The dialog shows completely

**Screenshots:**
<img width="355" alt="Invite users" src="https://user-images.githubusercontent.com/46905241/125999749-972b3fd0-01ed-4a85-b9c3-665dfff5cd21.png">

**Platform:**
 - Focalboard personal server v0.8.0

**Additional context:**
This is a regression.

**Comment by chenilim** [comment]
Hi @hahmadia, one more to investigate. Likely due to a recent CSS change.

**Comment by kamre** [comment]
Regression is very similar to #641 and is caused by #447 when `z-index` of `.top-head` [was changed to 100](https://github.com/mattermost/focalboard/pull/447/files#diff-a34f365f7de9366f36e3c1cdaf54c6242bbe315b4341ee50ecc9a3d2e6184550R46) while `Modal` wrapper that is used for invite users dialog [has only 10](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/modal.scss#L5) for `z-index`.
