### ISSUE TITLE
Bug: page reload loop 

### ISSUE THREAD

**Issue by arunzco** [mattermost/focalboard#747]
**Summary:**
Focalboard page keeps reloading on attempt to change password from focalboard menu 

**Steps to reproduce the behavior:**
1. Go to Focalboard
2. Click on Focalboard menu
3. Click on Change password , cancel it 
4. the page keeps reloading 

**Screenshots:**
https://gyazo.com/5e728799d04f30c496a7e3bc90eda9c7

**Platform:**
 - Bitnami Stack Mattermost 5.37  plugin 0.8.0
 
Hosted in Ubuntu with nginx

**Comment by chenilim** [comment]
Thanks @arunzco! The account actions are actually not valid on the plugin. This should be resolved with the fix for #739, which will hide those account actions on the plugin.

That said, there is an issue where navigating to `https://server/plugins/focalboard` results in an invite loop reload. This should be resolved in a future iteration of the plugin system.

Closing this as a dup for now.
