### ISSUE TITLE
Bug: Close button on cards doesn't appear on shared boards

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#888]
**Steps to reproduce the behavior:**
1. Share a board
2. Open the shared link
3. Open a card (or see [this card for reference](https://community.mattermost.com/plugins/focalboard/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8&r=762db9c6-305c-4d13-8ce6-9f11e5232c24&c=fab73592-3c32-4a03-8f19-fa1ae783ea67)
4. There's no close button

**Expected behavior:**
There should be a close button, just like the read-write card

**Screenshots:**
UI for read-only shared card:
<img width="452" alt="Shared card" src="https://user-images.githubusercontent.com/46905241/128379609-e52fed87-ea5f-4b63-b86e-f1dd97e45bc8.png">

UI for read-write card:
<img width="452" alt="RW card" src="https://user-images.githubusercontent.com/46905241/128379615-2d179107-4ac6-41c3-9383-ddce4ba9a312.png">

**Platform:**
 - Focalboard plugin v0.8.2 (community server)
 - Chrom 91 on macOS

**Additional context:**

**Comment by Shahzayb** [comment]
I'd take on this.

**Comment by Shahzayb** [comment]
`toolsMenu` is false because the shared board is `readonly`

https://github.com/mattermost/focalboard/blob/8fff482daab3a7b9c62bdc1d23e2ffc23289d6d9/webapp/src/app.tsx#L81-L83

https://github.com/mattermost/focalboard/blob/8fff482daab3a7b9c62bdc1d23e2ffc23289d6d9/webapp/src/components/cardDialog.tsx#L84-L87

if `toolsMenu` is false then it will hide the `close button` and `more options` button.

https://github.com/mattermost/focalboard/blob/8fff482daab3a7b9c62bdc1d23e2ffc23289d6d9/webapp/src/components/dialog.tsx#L42-L59
