### ISSUE TITLE
Feature Idea: Alternative install option

### ISSUE THREAD

**Issue by aranwe** [mattermost/focalboard#911]
**Summary:**
Ability to install outside of Windows Store / AppStore.

**How important this is to me and why:**
In our enterprise we have disabled Windows Store & we cannot install software directly from WS. 
Being able to install focalboard outside of WS would actually make us able to evaluate and eventually move to FB :)  

Importance: High

Use cases:
1. Install FB Desktop from Github .msi or .exe file.
2. Similar approach for other platforms.

**Additional context / similar features:**
I believe that adding .msi/.exe (& packages for other platforms) to Releases here on Github during the Release process would be the most simple/useful process.

**Comment by tjbortz1s** [comment]
Also this would let us update to 0.8.2 using the releases files instead of waiting for the windows store to update - right now it's not being published at all to the windows store and 0.8.0 has a lot of pretty broken "features" in it right now.

**Comment by chenilim** [comment]
Cleaning up old issues. This has been resolved for Windows: a zip file is included in each release, e.g. `focalboard-win.zip` in https://github.com/mattermost/focalboard/releases/tag/v0.9.2.

At this time we also publishing unsigned Mac App builds in release candidates, but not signed ones in release. Mainly due to the difficulty of automating the signing process. Most of the feedback to date has been around issues with the Windows App Store. Please chime in here if you are unable to access to Mac App Store, and we will reassess in the future. Thanks!
