### ISSUE TITLE
Bug: Table column calculations > Every "Created time" property field is counted as unique

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#912]
**Summary:**
Every field is the "Created time" field is count as a unique property. 
See the example in the screenshot - there's 6 rows but only 2 unique values:
-  _July 29, 12:06 AM_ 
- _August 09, 9:28PM_

I would expect the count to show **2**, not **6**.

**Steps to reproduce the behavior:**
1. Go to table view
2. Add a "Created time" property (or "Last Updated Time")
3. Create several cards in the table
4. In the "Created time" column, click _Calculate_ > _Count Unique Values_

**Expected behavior:**
Unique Count should show the number of unique values, not the total number of entries.

**Screenshots:**

![created_time](https://user-images.githubusercontent.com/15314183/128863496-1c693a9a-a4c3-4ae7-8a4c-e8a6d0c3c390.jpg)

**Comment by Johennes** [comment]
I think the problem is that date fields are stored in milliseconds but the UI only shows the time part down to the minute. The values of "Created time" and "Last updated time" properties are populated automatically so even though you see "12:06 AM" three times, the second / millisecond components will be different under the hood.

While the count is technically correct, the UI makes it seem misleading so I suppose we should transform these two properties to drop the non-displayed time components before applying the aggregation.

NB: Notion appears to do the counting as you'd expect based on the UI in this case:

![Screenshot 2021-08-12 at 22 17 12](https://user-images.githubusercontent.com/1137962/129263677-cb9f994f-b3e7-4846-929c-83e7f316e8a4.png)
