### ISSUE TITLE
Feature Request: Offer download of compiled binaries for Focalboard Personal Desktop 

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#99]
Feedback from HackerNews: https://news.ycombinator.com/item?id=26499443

We can perhaps look at adding binaries from our build system for the desktop and server editions, and perhaps add some instructions too. 

Wondering if the core committers produced the binaries, would there be people in the community interested in helping us draft the install guides for different platforms?

**Comment by Otiel** [comment]
I'm in an offline environment, no access to the Windows Store. Would love to try the Windows desktop app.

Not sure what you're expecting for the install guide (it should be straightforward anyway if you publish a setup file), but I can try to offer assistance.

**Comment by jespino** [comment]
The desktop edition is available for download as part of our release process, but probably we can add that in the releases page for Windows and Mac apps. @chenilim can you add that?

**Comment by it33** [comment]
So exciting to have feature requests!!

**Comment by chenilim** [comment]
I've added a zip file with signed Windows binaries to the [release]https://github.com/mattermost/focalboard/releases/tag/v0.6.1):
* Download `focalboard-win.zip`
* Unpack it
* Run `Focalboard.exe`

Also added [package-zip.bat](https://github.com/mattermost/focalboard/blob/main/win-wpf/package-zip.bat) as part of `make win-wpf-app`.

Please LMK or file an issue if you run into problems installing.

I'm hearing clear feedback that some folks have real issues with the Windows App Store. It's funny because we invested in building the App Store apps to make installing and updating much easier. If you can use the App Store, I highly recommend that route. I'm curious if this is mainly a Windows thing, so please file a new issue if anyone has similar issues with the Mac App Store.

**Comment by cameronconner** [comment]
Where are binaries for Mac? I see the Win and Linux ones. Can we get non-app store version for Mac? Interested in this for my company, but no interest in having to set up apple store stuff for everyone... Or, is there a web app I'm missing?
Thanks!

**Comment by austinsonger** [comment]
It's crazy that you don't add the binaries here... My work Macbook is blocked from downloading anything from Apple Store and linking itunes account to Macbook and the only way I can download apps is through github or the web.

**Comment by yusufmalikul** [comment]
Please add binaries for Mac.

I tried to download it from the App Store but it says "The App is not available in your country or region".
